title: Tweeting Babbage
hero_image: images/banner.png
description: Tweet messages and pictures from your Raspberry Pi
original_url: https://www.raspberrypi.org/learning/tweeting-babbage/
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: developer, design-0, programming-3, phys-comp-2, manufacture-0, community-0
interests: "photography, social media"
technologies: "python, twitter, picamera"
steps:
  - title: Introduction
  - title: What you'll need
  - title: Taking pictures
  - title: Taking pictures with a button
  - title: Tweeting photos and text
  - title: Modding your cuddly toy
  - title: What next?
